import { Component, useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { Experience } from '../experience/Experience';
import { chapterAt, chapters, goTo, journey } from '../data/journey';
import { gameReels, webReels } from '../data/projects';
import { money, productKeys, services, storeItems } from '../data/store';
import { useProgress } from '@react-three/drei';
import { setAmbientSound } from './sound';
import { MangoGame } from './MangoGame';
import { CatchToast } from './CatchToast';
import { BriefForm } from './BriefForm';
import { LoaderFacts } from './LoaderFacts';
import { getLang, setLang, useLang, type Lang, type Tx } from '../i18n';
class WorldBoundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true};}render(){const es=getLang()==='es';return this.state.error?<div className="fallback"><h1>{es?'Una pausa en el paraíso.':'A little pause in paradise.'}</h1><p>{es?'El mundo 3D no pudo arrancar. Activa la aceleración por hardware y recarga.':'The 3D world could not start. Enable hardware acceleration, then reload.'}</p><button onClick={()=>location.reload()}>{es?'Intentar de nuevo':'Try again'}</button></div>:this.props.children;}}
type Detail={label:Tx;title:Tx;copy:Tx;foot:Tx};
const details:Record<string,Detail>={
 games:{label:{en:'GAMES',es:'JUEGOS'},title:{en:'A place for play.',es:'Un lugar para jugar.'},copy:{en:'Worlds you can get lost in: multiplayer card tables, a plush universe, a dark fantasy saga and a farm that never sleeps.',es:'Mundos para perderse: mesas de cartas multijugador, un universo de peluches, una saga de fantasía oscura y una granja que nunca duerme.'},foot:{en:'Each project opens in a new tab.',es:'Cada proyecto se abre en una pestaña nueva.'}},
 web:{label:{en:'WEBS & APPS',es:'WEBS Y APPS'},title:{en:'Useful can be delightful.',es:'Lo útil también puede ser bonito.'},copy:{en:'Tools people open every day: fast, clear and with a little personality.',es:'Herramientas que la gente abre todos los días: rápidas, claras y con un poquito de personalidad.'},foot:{en:'Have a digital idea? Let’s find its shape.',es:'¿Tienes una idea digital? Busquémosle la forma.'}},
 about:{label:{en:'ABOUT SQUEEZY LABS',es:'SOBRE SQUEEZY LABS'},title:{en:'A small lab. An open horizon.',es:'Un laboratorio pequeño. Un horizonte abierto.'},copy:{en:'Squeezy Labs is a creative digital studio making games, websites, apps and experimental experiences. Our world takes its warmth, color and curiosity from the Caribbean.',es:'Squeezy Labs es un estudio digital creativo que hace juegos, webs, apps y experiencias experimentales. Nuestro mundo toma su calidez, su color y su curiosidad del Caribe.'},foot:{en:'Made in the Caribbean. Built for everywhere. 3D birds: “Seagull” by Dayvable and “Scarlet Macaw” by Mateus Schwaab (CC BY 4.0, Sketchfab).',es:'Hecho en el Caribe. Para todo el mundo. Aves 3D: “Seagull” de Dayvable y “Scarlet Macaw” de Mateus Schwaab (CC BY 4.0, Sketchfab).'}},
 contact:{label:{en:'LA LIBRETA / CUSTOM WORK',es:'LA LIBRETA / POR ENCARGO'},title:{en:'What should we write down?',es:'¿Qué anotamos?'},copy:{en:'Tell us what you have in mind: a website, an app, a game or something a little unusual. We reply within 48 hours.',es:'Cuéntanos qué tienes en mente: una web, una app, un juego o algo un poco fuera de lo común. Respondemos en 48 horas.'},foot:{en:'The form opens your email app with the message ready to send.',es:'El formulario abre tu correo con el mensaje listo para enviar.'}},
 shop:{label:{en:'LA BODEGA / THE SHELF',es:'LA BODEGA / EL ESTANTE'},title:{en:'Take something home.',es:'Llévate algo.'},copy:{en:'A prototype shelf of digital ideas. Explore the demos or tell us what we can build for you.',es:'Un estante de ideas digitales en prototipo. Mira los demos o dinos qué podemos hacer por ti.'},foot:{en:'Products and prices are placeholders until the catalog is approved.',es:'Productos y precios son de muestra hasta que se apruebe el catálogo.'}},
 cart:{label:{en:'LA BODEGA / YOUR TAB',es:'LA BODEGA / TU CUENTA'},title:{en:'La cuenta.',es:'La cuenta.'},copy:{en:'Everything you picked from the shelf.',es:'Todo lo que agarraste del estante.'},foot:{en:'Prototype checkout: no payment provider is connected and nothing is charged.',es:'Pago de prueba: no hay pasarela conectada y no se cobra nada.'}},
};
const ctaFor:Record<string,{text:Tx;modal:string;pill?:boolean}>={
 'Games':{text:{en:'Meet our playful side',es:'Conoce nuestro lado juguetón'},modal:'games'},
 'Web & apps':{text:{en:'Explore our digital side',es:'Mira nuestro lado digital'},modal:'web'},
 'La bodega':{text:{en:'Order your project',es:'Encarga tu proyecto'},modal:'contact',pill:true},
 'The bigger picture':{text:{en:'Let’s make something',es:'Hagamos algo juntos'},modal:'contact',pill:true},
};
// Short interface strings.
const T={
 en:{loading:'Loading the world…',preparing:'Preparing the world…',loadingAria:'World loading',loaderNote:'A little closer to somewhere good.',hello:'¡Epa! Come on in.',helloQ:'What can we get you?',helloAria:'Message from Squeezy',closeHello:'Close welcome',seeShelf:'See the shelf',home:'Squeezy Labs, back to the bodega',nav:'Main navigation',projects:'Projects',about:'About',tab:'Tab',tabAria:(n:number,m:string)=>`Your tab: ${n} items, ${m}`,talk:'Let’s talk',scrollAria:'Scroll to explore the Squeezy world',locSmall:'CARIBBEAN ROOTS. OPEN HORIZONS.',wander:'Scroll to wander',chaptersAria:'Journey chapters',soundOff:'Turn ambient sound off',soundOn:'Turn ambient sound on',resume:'Resume ambient animation',pause:'Pause ambient animation',meta:'INDEPENDENT BY NATURE',closeDialog:'Close dialog',demo:'Lab concept · demo catalog',onTab:(n:number)=>`On your tab (${n}) · add one more`,addTab:'Add to tab',orderCustom:'Order custom work',goTab:'Go to your tab',shelfNote:'Demo catalog. Prices are illustrative; nothing is on sale yet.',onTabShort:(n:number)=>`On tab (${n})`,orders:'Today’s orders',writeIt:'Write it in la libreta',payProto:'Prototype: this is where the payment provider would open. Nothing was charged.',empty:'Your tab is empty. Add something from the shelf first.',emptyShort:'Your tab is empty.',remove:'Remove one',addOne:'Add one',payWith:'Pay with',card:'Card',cardNote:'Visa or Mastercard, from any country.',zelleNote:'We send the address for the transfer.',pmNote:'In bolívares at the BCV rate of the day.',pay:'Pay',name:'Your name',namePh:'A name to say hello to',email:'Email',idea:'What are you thinking?',ideaPh:'A game, an app, something a little unusual…',send:'Send by email',sent:'Your email app should be open with the message ready. If it did not open, write to',orWrite:'Or write to us directly:',start:'Start a conversation',chapter:'Chapter',reduced:'Reduced motion enabled.',subject:'Project for Squeezy Labs',langSwitch:'Ver en español'},
 es:{loading:'Cargando el mundo…',preparing:'Preparando el mundo…',loadingAria:'Cargando el mundo',loaderNote:'Un poquito más cerca de algo bueno.',hello:'¡Epa! Pase adelante.',helloQ:'¿Qué le provoca?',helloAria:'Mensaje de Squeezy',closeHello:'Cerrar bienvenida',seeShelf:'Ver el estante',home:'Squeezy Labs, volver a la bodega',nav:'Navegación principal',projects:'Proyectos',about:'Nosotros',tab:'Cuenta',tabAria:(n:number,m:string)=>`Tu cuenta: ${n} productos, ${m}`,talk:'Hablemos',scrollAria:'Desplázate para explorar el mundo Squeezy',locSmall:'RAÍCES CARIBEÑAS. HORIZONTES ABIERTOS.',wander:'Desplázate para pasear',chaptersAria:'Capítulos del recorrido',soundOff:'Apagar el sonido ambiente',soundOn:'Encender el sonido ambiente',resume:'Reanudar la animación',pause:'Pausar la animación',meta:'INDEPENDIENTE POR NATURALEZA',closeDialog:'Cerrar',demo:'Concepto del laboratorio · catálogo de demostración',onTab:(n:number)=>`En tu cuenta (${n}) · agregar otro`,addTab:'Agregar a la cuenta',orderCustom:'Encargar algo a medida',goTab:'Ir a tu cuenta',shelfNote:'Catálogo de demostración. Los precios son ilustrativos; ningún producto está a la venta todavía.',onTabShort:(n:number)=>`En la cuenta (${n})`,orders:'Encargos del día',writeIt:'Anótalo en la libreta',payProto:'Prototipo: aquí se abriría la pasarela de pago. No se cobró nada.',empty:'Tu cuenta está vacía. Agrega algo del estante primero.',emptyShort:'Tu cuenta está vacía.',remove:'Quitar uno de',addOne:'Agregar uno de',payWith:'Pagar con',card:'Tarjeta',cardNote:'Visa o Mastercard, desde cualquier país.',zelleNote:'Te enviamos el correo para la transferencia.',pmNote:'En bolívares a la tasa BCV del día.',pay:'Pagar',name:'Tu nombre',namePh:'Un nombre para saludarte',email:'Correo',idea:'¿Qué tienes en mente?',ideaPh:'Un juego, una app, algo fuera de lo común…',send:'Enviar por correo',sent:'Se debería haber abierto tu correo con el mensaje listo. Si no se abrió, escríbenos a',orWrite:'O escríbenos directo:',start:'Empezar una conversación',chapter:'Capítulo',reduced:'Movimiento reducido activado.',subject:'Proyecto para Squeezy Labs',langSwitch:'View in English'},
};
const LangToggle=({lang}:{lang:Lang})=><button className="lang-toggle" onClick={()=>setLang(lang==='es'?'en':'es')} aria-label={T[lang].langSwitch}><b className={lang==='es'?'on':''}>ES</b><span>/</span><b className={lang==='en'?'on':''}>EN</b></button>;
export function App(){
 const lang=useLang(),t=T[lang],m=(n:number)=>money(n,lang);
 const {progress:assetProgress}=useProgress();
 const [ready,setReady]=useState(false),[progress,setProgress]=useState(0),[chapter,setChapter]=useState(0),[modal,setModal]=useState<string|null>(null),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false);
 const [sound,setSound]=useState(false);
 const [greet,setGreet]=useState(false),[dismissed,setDismissed]=useState(false);
 useEffect(()=>{if(!ready)return;const id=setTimeout(()=>setGreet(true),5200);return()=>clearTimeout(id);},[ready]);
 const [cart,setCart]=useState<Record<string,number>>({}),[payStatus,setPayStatus]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),lastFocus=useRef<HTMLElement|null>(null);
 const onReady=useCallback(()=>setReady(true),[]);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);journey.reduced=media.matches;};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{let frame=0;let last=0;const tick=(t:number)=>{if(t-last>65){setProgress(journey.rendered);setChapter(chapterAt(journey.rendered));document.body.classList.toggle('travelling',Math.abs(journey.progress-journey.rendered)>.004);last=t;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);document.body.classList.remove('travelling');};},[]);
 useEffect(()=>{if(modal){lastFocus.current=document.activeElement as HTMLElement;if(!dialog.current?.open)dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';lastFocus.current?.focus();}return()=>{document.body.style.overflow='';};},[modal]);
 // Dev only: ?p=0.82 jumps straight to a point on the journey for screenshots.
 useEffect(()=>{if(!import.meta.env.DEV||!ready)return;const p=new URLSearchParams(location.search).get('p');if(p===null)return;const v=+p;window.scrollTo(0,v*(document.documentElement.scrollHeight-innerHeight));journey.progress=journey.rendered=v;},[ready]);
 const open=useCallback((name:string)=>{setPayStatus('');setModal(name);},[]);
 const select=useCallback((key:string)=>{const item=storeItems[key];if(!item)return open(key);open(item.kind==='hire'?'contact':'item:'+key);},[open]);
 const add=(key:string)=>setCart(c=>({...c,[key]:(c[key]||0)+1}));
 const change=(key:string,d:number)=>setCart(c=>{const n={...c,[key]:Math.max(0,(c[key]||0)+d)};if(!n[key])delete n[key];return n;});
 const count=Object.values(cart).reduce((a,b)=>a+b,0),total=Object.entries(cart).reduce((a,[k,q])=>a+q*(storeItems[k].price||0),0);
 const c=chapters[chapter],cta=ctaFor[c.name];
 const item=modal?.startsWith('item:')?storeItems[modal.slice(5)]:null,itemKey=modal?.slice(5)||'';
 const info=modal&&!item?details[modal]:null;
 return <>
 <WorldBoundary><Experience onReady={onReady} onSelect={select}/><CatchToast onOpen={open}/></WorldBoundary>
 <div className={`loader ${ready?'loaded':''}`} aria-hidden={ready}><img className="loader-symbol" src="/brand/squeezy-512.png" alt="Squeezy Labs"/><p>{!ready&&assetProgress>=100?t.preparing:`${t.loading} ${Math.round(ready?100:assetProgress)}%`}</p><div className="load-line" role="progressbar" aria-label={t.loadingAria} aria-valuenow={Math.round(ready?100:assetProgress)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${ready?100:assetProgress}%`}}/></div><LoaderFacts lang={lang}/></div>
 <div className="vignette"/>
 {ready&&greet&&!dismissed&&progress<.105&&<aside className="transmission" aria-label={t.helloAria}><div><span className="signal-dot"/> LA BODEGA / SQUEEZY LABS<button aria-label={t.closeHello} onClick={()=>setDismissed(true)}>×</button></div><p>{t.hello}<br/><em>{t.helloQ}</em></p><button className="text-button" onClick={()=>open('shop')}>{t.seeShelf} ↗</button></aside>}
 <header className="header"><button className="wordmark logo-only" onClick={()=>goTo(0)} aria-label={t.home}><img className="brand-symbol" src="/brand/squeezy-512.png" alt="Squeezy Labs"/></button><nav aria-label={t.nav}><button onClick={()=>goTo(chapters[1].progress)}>{t.projects}</button><button onClick={()=>goTo(chapters[0].progress)}>Bodega</button><button onClick={()=>open('about')}>{t.about}</button><button className="tab-nav" onClick={()=>open('cart')} aria-label={t.tabAria(count,m(total))}>{t.tab} <b>{count}</b></button><LangToggle lang={lang}/><button className="contact-nav" onClick={()=>open('contact')}>{t.talk} <span>↗</span></button></nav></header>
 <main className="scroll-track" aria-label={t.scrollAria}><div className="chapter-content" key={chapter+lang}><p className="eyebrow">{c.label[lang]}</p><h1>{c.title[lang].split('\n').map((line,i)=><span key={i}>{line}</span>)}</h1><p className="chapter-copy">{c.copy[lang]}</p>
 {cta.pill?<button className="pill" onClick={()=>open(cta.modal)}>{cta.text[lang]} <span>↗</span></button>:<button className="text-button" onClick={()=>open(cta.modal)}>{cta.text[lang]} <span>↗</span></button>}
 {c.name==='La bodega'&&<button className="text-button bodega-alt" onClick={()=>open('shop')}>{t.seeShelf} <span>↗</span></button>}
 </div></main>
 <aside className="location"><span className="location-icon">✳</span><div>{lang==='es'?'Algún lugar del Caribe':'Somewhere in the Caribbean'}<small>{t.locSmall}</small></div></aside>
 <div className="side-progress" aria-hidden="true"><span>{String(chapter+1).padStart(2,'0')}</span><i><b style={{height:`${progress*100}%`}}/></i><span>{String(chapters.length).padStart(2,'0')}</span></div>
 <footer className="journey-bar"><span className="scroll-hint"><span className="mouse-icon"/> {t.wander}</span><nav aria-label={t.chaptersAria}>{chapters.map((ch,i)=><button key={ch.name} onClick={()=>goTo(ch.progress)} className={chapter===i?'active':''} aria-current={chapter===i?'step':undefined}><span className="chapter-number">0{i+1}</span><span>{ch.short[lang]}</span></button>)}</nav><button className="motion-button sound-button" onClick={()=>{setAmbientSound(!sound);setSound(!sound);}} aria-pressed={sound} aria-label={sound?t.soundOff:t.soundOn}>{sound?'♪':'♫'}</button><button className="motion-button" onClick={()=>{journey.paused=!paused;setPaused(!paused);}} aria-pressed={paused} aria-label={paused?t.resume:t.pause}>{paused?'▷':'Ⅱ'}</button></footer>
 <div className="bottom-meta"><span>{t.meta}</span><span>10° N / 66° W <i>✳</i></span></div>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null);}}><div className="dialog-inner"><button className="close" onClick={()=>setModal(null)} aria-label={t.closeDialog}>×</button>
 {item&&<><p className="prototype-note">{t.demo}</p><p className="eyebrow">{item.type[lang].toUpperCase()}</p><h2>{item.name[lang]}</h2><p>{item.desc[lang]}</p>
  {item.kind==='product'?<div className="item-row"><strong>{m(item.price||0)}</strong><button className="pill" onClick={()=>add(itemKey)}>{cart[itemKey]?t.onTab(cart[itemKey]):t.addTab} <span>+</span></button></div>
  :<div className="item-row"><button className="pill" onClick={()=>open('shop')}>{t.seeShelf} <span>↗</span></button><button className="text-button dark" onClick={()=>open('contact')}>{t.orderCustom} ↗</button></div>}
  {item.kind==='product'&&count>0&&<button className="text-button dark" onClick={()=>open('cart')}>{t.goTab} ({count}) ↗</button>}</>}
 {info&&<><p className="eyebrow">{info.label[lang]}</p><h2>{info.title[lang]}</h2><p>{info.copy[lang]}</p>
  {(modal==='games'||modal==='web')&&<ul className="work">{(modal==='games'?gameReels:webReels).map(p=><li key={p.id}><a href={p.url} target="_blank" rel="noopener noreferrer"><img src={`/projects/${p.id}.webp`} alt="" loading="lazy"/><span><b>{p.title}{p.status&&<small>{p.status[lang]}</small>}</b>{p.blurb[lang]}</span><i>↗</i></a></li>)}</ul>}
  {modal==='games'&&<MangoGame/>}
  {modal==='shop'&&<><p className="prototype-note">{t.shelfNote}</p><div className="shelf">{productKeys.map(k=>{const p=storeItems[k],pk=p.pack!;return <article key={k} className="shelf-item"><div className="pack" style={{background:pk.bg,color:pk.fg}}><small>{pk.top}</small><span className="pt">{pk.t1}<i>{pk.t2}</i></span><span className="sticker">{m(p.price||0)}</span></div><h3>{p.name[lang]}</h3><p>{p.desc[lang]}</p><button className="pill" onClick={()=>add(k)}>{cart[k]?t.onTabShort(cart[k]):t.addTab} <span>+</span></button></article>;})}</div>
   <div className="board"><h3>{t.orders}</h3><ul>{services.map(s=><li key={s.name.en}><b>{s.name[lang]}</b><span>{s.price[lang]}</span><small>{s.note[lang]}</small></li>)}</ul><button className="pill" onClick={()=>open('contact')}>{t.writeIt} <span>↗</span></button></div>
   {count>0&&<button className="text-button dark" onClick={()=>open('cart')}>{t.goTab} ({count} · {m(total)}) ↗</button>}</>}
  {modal==='cart'&&<form className="pay" onSubmit={e=>{e.preventDefault();setPayStatus(count?t.payProto:t.empty);}}>
   <div className="ticket">{count===0?<p>{t.emptyShort}</p>:Object.entries(cart).map(([k,q])=><div className="ticket-row" key={k}><span>{storeItems[k].name[lang]}</span><span className="qty"><button type="button" onClick={()=>change(k,-1)} aria-label={`${t.remove} ${storeItems[k].name[lang]}`}>−</button>{q}<button type="button" onClick={()=>change(k,1)} aria-label={`${t.addOne} ${storeItems[k].name[lang]}`}>+</button></span><span>{m(q*(storeItems[k].price||0))}</span></div>)}<div className="ticket-total"><span>Total</span><span>{m(total)}</span></div></div>
   <fieldset><legend>{t.payWith}</legend><label className="opt"><input type="radio" name="pm" defaultChecked/> {t.card} <small>{t.cardNote}</small></label><label className="opt"><input type="radio" name="pm"/> Zelle <small>{t.zelleNote}</small></label><label className="opt"><input type="radio" name="pm"/> Pago móvil <small>{t.pmNote}</small></label></fieldset>
   <button className="pill" type="submit">{t.pay} {m(total)}</button>{payStatus&&<p role="status" className="success">{payStatus}</p>}</form>}
  {modal==='contact'&&<BriefForm key={lang} lang={lang}/>}
  <p className="dialog-foot">{info.foot[lang]}</p>{modal!=='contact'&&<button className="text-button dark" onClick={()=>open('contact')}>{t.start} ↗</button>}</>}
 </div></dialog>
 <span className="sr-only" role="status">{t.chapter} {chapter+1}: {c.short[lang]}{reduced?'. '+t.reduced:''}</span>
 </>;
}
