import { Component, useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { Experience } from '../experience/Experience';
import { chapters, goTo, journey } from '../data/journey';
import { useProgress } from '@react-three/drei';
class WorldBoundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true};}render(){return this.state.error?<div className="fallback"><h1>A little pause in paradise.</h1><p>The 3D world could not start. Enable hardware acceleration, then reload.</p><button onClick={()=>location.reload()}>Try again</button></div>:this.props.children;}}
const details:Record<string,{label:string;title:string;copy:string;foot:string}>={
 games:{label:'GAMES / WORK IN PROGRESS',title:'A place for play.',copy:'We make worlds you can get lost in, and little moments that stay with you. This coastal arcade is the first home for our future game projects.',foot:'Project showcase coming soon. No game releases are announced here.'},
 web:{label:'WEBS & APPS',title:'Useful can be delightful.',copy:'Websites, apps and digital products with a little personality. Thoughtful interfaces, playful details, and experiences that feel good to use.',foot:'Have a digital idea? Let’s find its shape.'},
 experiments:{label:'THE EXPERIMENT SHELF',title:'Curiosity, on repeat.',copy:'Some ideas start without a brief. A squishy shape. An unexpected interaction. A tiny prototype that turns into something bigger.',foot:'Try squeezing the little experiment below.'},
 about:{label:'ABOUT SQUEEZY LABS',title:'A small lab. An open horizon.',copy:'Squeezy Labs is a creative digital studio making games, websites, apps and experimental experiences. Our world takes its warmth, color and curiosity from Venezuela.',foot:'Made in Venezuela. Built for everywhere.'},
 contact:{label:'LET’S MAKE SOMETHING',title:'Big idea? Small curiosity?',copy:'Tell us what you have in mind. Save a project brief below to start the conversation.',foot:'This is a first prototype. Contact delivery is not connected yet; your brief stays on your device.'},
};
export function App(){
 const {progress:assetProgress}=useProgress();
 const [ready,setReady]=useState(false),[progress,setProgress]=useState(0),[chapter,setChapter]=useState(0),[modal,setModal]=useState<string|null>(null),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[squeezed,setSqueezed]=useState(false),[saved,setSaved]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),lastFocus=useRef<HTMLElement|null>(null);
 const onReady=useCallback(()=>setReady(true),[]);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);journey.reduced=media.matches;};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{let frame=0;let last=0;const tick=(t:number)=>{if(t-last>65){setProgress(journey.rendered);const p=journey.rendered;setChapter(p<.16?0:p<.37?1:p<.57?2:p<.81?3:4);last=t;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);
 useEffect(()=>{if(modal){lastFocus.current=document.activeElement as HTMLElement;dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';lastFocus.current?.focus();}return()=>{document.body.style.overflow='';};},[modal]);
 const open=(name:string)=>{setSaved(false);setModal(name);};
 const c=chapters[chapter];
 return <>
 <WorldBoundary><Experience onReady={onReady} onSelect={open}/></WorldBoundary>
 <div className={`loader ${ready?'loaded':''}`} aria-hidden={ready}><div className="loader-mark">squeezy<span>®</span></div><p>Loading the world… {Math.round(ready?100:assetProgress)}%</p><div className="load-line" role="progressbar" aria-label="World loading" aria-valuenow={Math.round(ready?100:assetProgress)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${ready?100:assetProgress}%`}}/></div><span className="loader-note">A little closer to somewhere good.</span></div>
 <div className="vignette"/>
 <header className="header"><button className="wordmark" onClick={()=>goTo(0)} aria-label="Squeezy Labs, back to arrival">squeezy<span className="wordmark-spark">✳</span><small>LABS</small></button><nav aria-label="Main navigation"><button onClick={()=>goTo(.23)}>Projects</button><button onClick={()=>goTo(.65)}>The lab</button><button onClick={()=>open('about')}>About</button><button className="contact-nav" onClick={()=>open('contact')}>Let’s talk <span>↗</span></button></nav></header>
 <main className="scroll-track" aria-label="Scroll to explore the Squeezy world"><div className="chapter-content" key={chapter}><p className="eyebrow">{c.label}</p><h1>{c.title.split('\n').map((line,i)=><span key={i}>{line}</span>)}</h1><p className="chapter-copy">{c.copy}</p>
 {chapter===0?<button className="pill" onClick={()=>goTo(.23)}>Explore the lab <span>↘</span></button>:chapter===4?<button className="pill" onClick={()=>open('contact')}>Let’s make something <span>↗</span></button>:<button className="text-button" onClick={()=>open(chapter===1?'games':chapter===2?'web':'experiments')}>{chapter===1?'Meet our playful side':chapter===2?'Explore our digital side':'Take a closer look'} <span>↗</span></button>}
 </div></main>
 <aside className="location"><span className="location-icon">✳</span><div>Somewhere in the Caribbean<small>VENEZUELAN ROOTS. OPEN HORIZONS.</small></div></aside>
 <div className="side-progress" aria-hidden="true"><span>{String(chapter+1).padStart(2,'0')}</span><i><b style={{height:`${progress*100}%`}}/></i><span>05</span></div>
 <footer className="journey-bar"><span className="scroll-hint"><span className="mouse-icon"/> Scroll to wander</span><nav aria-label="Journey chapters">{chapters.map((item,i)=><button key={item.name} onClick={()=>goTo(item.progress)} className={chapter===i?'active':''} aria-current={chapter===i?'step':undefined}><span className="chapter-number">0{i+1}</span><span>{i===4?'Horizon':item.name}</span></button>)}</nav><button className="motion-button" onClick={()=>{journey.paused=!paused;setPaused(!paused);}} aria-pressed={paused} aria-label={paused?'Resume ambient animation':'Pause ambient animation'}>{paused?'▷':'Ⅱ'}</button></footer>
 <div className="bottom-meta"><span>INDEPENDENT BY NATURE</span><span>10° N / 66° W <i>✳</i></span></div>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null);}}><div className="dialog-inner"><button className="close" onClick={()=>setModal(null)} aria-label="Close dialog">×</button>{modal&&<><p className="eyebrow">{details[modal].label}</p><h2>{details[modal].title}</h2><p>{details[modal].copy}</p>{modal==='experiments'&&<button className={`squeeze-toy ${squeezed?'squeezed':''}`} onClick={()=>{setSqueezed(true);setTimeout(()=>setSqueezed(false),650);}} aria-label="Squeeze the experiment">✳</button>}{modal==='contact'&&<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const text=`Squeezy Labs — Project brief\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('idea')}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='squeezy-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setSaved(true);}}><label>Your name<input name="name" autoComplete="name" required placeholder="A name to say hello to"/></label><label>Email<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label><label>What are you thinking?<textarea name="idea" required rows={3} placeholder="A game, an app, something a little unusual…"/></label><button className="pill" type="submit">Save my project brief</button>{saved&&<p role="status" className="success">Your brief is saved. Nothing has been sent.</p>}</form>}<p className="dialog-foot">{details[modal].foot}</p>{modal!=='contact'&&<button className="text-button dark" onClick={()=>open('contact')}>Start a conversation ↗</button>}</>}</div></dialog>
 <span className="sr-only" role="status">Chapter {chapter+1}: {c.name}{reduced?'. Reduced motion enabled.':''}</span>
 </>;
}
