import { useLayoutEffect, useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { BufferGeometry, CanvasTexture, Color, CylinderGeometry, DoubleSide, Float32BufferAttribute, Group, InstancedMesh, Object3D, Quaternion, SRGBColorSpace, Vector3 } from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { journey } from '../data/journey';
const random=(i:number)=>{const n=Math.sin(i*127.1+78.233)*43758.5453;return n-Math.floor(n);};
const leaf=new BufferGeometry();const p:number[]=[],uv:number[]=[],indices:number[]=[];
for(let j=0;j<=10;j++){const t=j/10;for(let s=0;s<3;s++){const side=s-1,w=Math.pow(Math.sin(t*Math.PI),.72);p.push(side*w*.52,Math.sin(t*Math.PI)*.1-Math.abs(side)*w*.07,t*1.8);uv.push(s/2,t);if(j<10&&s<2){const n=j*3+s;indices.push(n,n+3,n+1,n+1,n+3,n+4);}}}leaf.setAttribute('position',new Float32BufferAttribute(p,3));leaf.setAttribute('uv',new Float32BufferAttribute(uv,2));leaf.setIndex(indices);leaf.computeVertexNormals();
let leafMap:CanvasTexture;
function foliageMap(){if(leafMap)return leafMap;const canvas=document.createElement('canvas');canvas.width=128;canvas.height=256;const c=canvas.getContext('2d')!;const grad=c.createLinearGradient(0,0,128,0);grad.addColorStop(0,'#718d42');grad.addColorStop(.45,'#bac66a');grad.addColorStop(.52,'#93ab54');grad.addColorStop(1,'#5b813d');c.fillStyle=grad;c.fillRect(0,0,128,256);c.strokeStyle='#d1c98a80';c.lineWidth=1.1;c.beginPath();c.moveTo(64,0);c.lineTo(64,256);c.stroke();for(let i=1;i<13;i++){c.strokeStyle='#d9d58a35';c.beginPath();c.moveTo(64,i*21);c.quadraticCurveTo(32,i*21-10,0,i*21-37);c.moveTo(64,i*21);c.quadraticCurveTo(96,i*21-10,128,i*21-37);c.stroke();}leafMap=new CanvasTexture(canvas);leafMap.colorSpace=SRGBColorSpace;return leafMap;}
export function NaturalShrub({position,scale=1,seed=0,flowers=false}:{position:[number,number,number];scale?:number;seed?:number;flowers?:boolean}){
 const ref=useRef<InstancedMesh>(null),blooms=useRef<InstancedMesh>(null),group=useRef<Group>(null);const count=192;
 const branches=useMemo(()=>{const geometries=[];for(let b=0;b<16;b++){const a=b*2.399+seed,length=.6+random(b+seed)*.7;const end=new Vector3(Math.cos(a)*length,.55+random(b+seed+31)*.7,Math.sin(a)*length),start=new Vector3(0,.06,0),dir=end.clone().sub(start);const g=new CylinderGeometry(.008,.025,dir.length(),5);g.applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0,1,0),dir.clone().normalize()));g.translate(end.x*.5,end.y*.5,end.z*.5);geometries.push(g);}return mergeGeometries(geometries);},[seed]);
 useLayoutEffect(()=>{const o=new Object3D();for(let i=0;i<count;i++){const b=Math.floor(i/12),k=i%12,a=b*2.399+seed,length=.6+random(b+seed)*.7,t=.32+(k/12)*.68,side=k%2?1:-1;o.position.set(Math.cos(a)*length*t+Math.sin(a)*side*.08,(.55+random(b+seed+31)*.7)*t,Math.sin(a)*length*t-Math.cos(a)*side*.08);o.rotation.set(-.15+random(i+seed)*.55,a+side*1.0,random(i+21)*.55);const sz=.13+random(i+seed+40)*.13;o.scale.setScalar(sz);if(flowers&&i%5===0)o.scale.set(sz*.55,sz*.7,sz*.6);o.updateMatrix();ref.current!.setMatrixAt(i,o.matrix);ref.current!.setColorAt(i,new Color(flowers&&i%5===0?['#ff4e91','#ce246b','#f193b4'][i%3]:['#83975a','#a1b474','#687f4b','#bbbf83'][i%4]));}ref.current!.instanceMatrix.needsUpdate=true;},[seed,flowers]);
 useFrame(({clock})=>{if(group.current&&!journey.paused&&!journey.reduced)group.current.rotation.z=Math.sin(clock.elapsedTime*.65+seed)*.012;});
 useLayoutEffect(()=>{if(!flowers||!blooms.current)return;const o=new Object3D();for(let i=0;i<90;i++){const b=Math.floor(i/6),a=b*2.399+seed,l=.6+random(b+seed)*.7;o.position.set(Math.cos(a)*l,.55+random(b+seed+31)*.7,Math.sin(a)*l);o.rotation.set(i*.7,i*2.4,i*.3);o.scale.setScalar(.11+random(i)*.04);o.updateMatrix();blooms.current.setMatrixAt(i,o.matrix);blooms.current.setColorAt(i,new Color(['#d93275','#ef568f','#f28cb0'][i%3]));}blooms.current.instanceMatrix.needsUpdate=true;},[flowers,seed]);
 return <group ref={group} position={position} scale={scale}><mesh geometry={branches} castShadow><meshStandardMaterial color="#7a6849" roughness={1}/></mesh><instancedMesh ref={ref} args={[leaf,undefined,count]} castShadow receiveShadow><meshStandardMaterial map={foliageMap()} side={DoubleSide} roughness={.7} metalness={0} emissive="#314820" emissiveIntensity={.14}/></instancedMesh>{flowers&&<instancedMesh ref={blooms} args={[leaf,undefined,90]} castShadow><meshStandardMaterial side={DoubleSide} roughness={.85}/></instancedMesh>}</group>;
}
